### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by CrowdHailer** [4front/htmlprep#2]
I hope this is ok to open up as an issue.

I think this is a very interesting idea. I ended up with a solution similar to this at the end of my own chain of logic. What are the projects that you would consider most similar to this one? Would something like metalsmith qualify. It allows you to build your own transformations for html.

Do you use this in production? have you managed to employ it in several projects or is it tuned too one. 

Thanks if you have the time for any answers. it looks really interesting.

**Comment by dvonlehman** [comment]
@CrowdHailer, thanks for your interest. My main goal with htmlprep was to provide a lightweight streaming html pre-processor rather than a full-blown template engine (like EJS, Jade, Liquid, etc.) that requires a parsed representation of the document in memory.

The library is quite battle tested. Every page request to any of the thousands of websites hosted on www.aerobatic.com is processed by htmlprep at run time. Because it is a multi-tenant platform it was crucial that to be able to pipe the HTML response stream through the pre-processor as efficiently as possible to minimize loading latency and impacts on the other websites hosted on the platform.

Hope that's useful info.
